-- Migration: Create policy_extraction_queries table
-- Purpose: Store LLM-generated queries and AWS Textract responses with confidence scores
-- Date: 2025-11-12

-- Create policy_extraction_queries table
CREATE TABLE IF NOT EXISTS policy_extraction_queries (
    id SERIAL PRIMARY KEY,
    bank_id VARCHAR(50) NOT NULL,
    policy_type_id VARCHAR(50) NOT NULL,

    -- Query and response details
    query_text TEXT NOT NULL,
    response_text TEXT,
    confidence_score NUMERIC(5, 2), -- Textract confidence score (0-100)

    -- Metadata
    document_hash VARCHAR(64) NOT NULL,
    source_document VARCHAR(500),
    extraction_method VARCHAR(50) DEFAULT 'textract', -- textract, manual, etc.
    query_order INTEGER, -- Order in which query was generated

    -- Status
    is_active BOOLEAN DEFAULT TRUE,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Foreign keys
    CONSTRAINT fk_extraction_queries_bank
        FOREIGN KEY (bank_id)
        REFERENCES banks(bank_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_extraction_queries_policy_type
        FOREIGN KEY (policy_type_id)
        REFERENCES policy_types(policy_type_id)
        ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_extraction_queries_bank_policy
    ON policy_extraction_queries(bank_id, policy_type_id);

CREATE INDEX IF NOT EXISTS idx_extraction_queries_document_hash
    ON policy_extraction_queries(document_hash);

CREATE INDEX IF NOT EXISTS idx_extraction_queries_active
    ON policy_extraction_queries(is_active);

CREATE INDEX IF NOT EXISTS idx_extraction_queries_created_at
    ON policy_extraction_queries(created_at);

CREATE INDEX IF NOT EXISTS idx_extraction_queries_confidence
    ON policy_extraction_queries(confidence_score) WHERE confidence_score IS NOT NULL;

-- Add comments to table
COMMENT ON TABLE policy_extraction_queries IS 'Stores LLM-generated extraction queries and AWS Textract responses with confidence scores';

-- Add comments to columns
COMMENT ON COLUMN policy_extraction_queries.id IS 'Primary key';
COMMENT ON COLUMN policy_extraction_queries.bank_id IS 'Reference to the bank that owns this policy';
COMMENT ON COLUMN policy_extraction_queries.policy_type_id IS 'Reference to the policy type';
COMMENT ON COLUMN policy_extraction_queries.query_text IS 'The query text generated by LLM for data extraction';
COMMENT ON COLUMN policy_extraction_queries.response_text IS 'The extracted response from AWS Textract';
COMMENT ON COLUMN policy_extraction_queries.confidence_score IS 'Textract confidence score (0-100)';
COMMENT ON COLUMN policy_extraction_queries.document_hash IS 'Hash of the source document for linking to containers';
COMMENT ON COLUMN policy_extraction_queries.source_document IS 'Source document path or S3 URL';
COMMENT ON COLUMN policy_extraction_queries.extraction_method IS 'Method used for extraction (textract, manual, etc.)';
COMMENT ON COLUMN policy_extraction_queries.query_order IS 'Order in which query was generated';
COMMENT ON COLUMN policy_extraction_queries.is_active IS 'Whether this query is currently active';
COMMENT ON COLUMN policy_extraction_queries.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN policy_extraction_queries.updated_at IS 'Timestamp when the record was last updated';

-- Create function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_extraction_queries_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update updated_at
DROP TRIGGER IF EXISTS trigger_update_extraction_queries_timestamp ON policy_extraction_queries;
CREATE TRIGGER trigger_update_extraction_queries_timestamp
    BEFORE UPDATE ON policy_extraction_queries
    FOR EACH ROW
    EXECUTE FUNCTION update_extraction_queries_updated_at();

-- Grant permissions (adjust as needed for your setup)
GRANT SELECT, INSERT, UPDATE, DELETE ON policy_extraction_queries TO underwriting_user;
GRANT USAGE, SELECT ON SEQUENCE policy_extraction_queries_id_seq TO underwriting_user;

-- Display success message
DO $$
BEGIN
    RAISE NOTICE 'Migration completed successfully!';
    RAISE NOTICE 'Created table: policy_extraction_queries';
    RAISE NOTICE 'Created indexes: idx_extraction_queries_bank_policy, idx_extraction_queries_document_hash, idx_extraction_queries_active, idx_extraction_queries_created_at, idx_extraction_queries_confidence';
    RAISE NOTICE 'Created trigger: trigger_update_extraction_queries_timestamp';
END $$;
